channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pip=24.0
  - xgboost
  - pip:
      - configargparse
      - rdata
      - pysnptools
      - scikit-optimize
      - shap
      - matplotlib
      - openpyxl
