import rdata
import pandas as pd

class HealthAndExposure:
    def __init__(self, filename, type):
        self.rdata = self.parse_he_rdata(filename, type)

    def parse_he_rdata(self, rdatafile, type):
        converted = rdata.read_rda(str(rdatafile))
        df = next(iter(converted.values())) # convert into dataframe

        # extract fields
        cats = []
        cats.append("epr_number")
        cats.append("he_age_derived") # age (while answering the survey)
        cats.append("he_bmi_cat_derived")
        cats.append("he_a005_physical_health")
        cats.append("he_b007_hypertension_PARQ") # ever diagnosed with hypertension
        cats.append("he_b009_atherosclerosis")
        cats.append("he_b010_cardiac_arrhythmia")
        cats.append("he_b012_heart_attack")
        cats.append("he_b013_coronary_artery")
        cats.append("he_b014_congestive_heart_failure")
        cats.append("he_b015_poor_blood_flow")
        cats.append("he_b016_raynauds")
        cats.append("he_b017_blood_clots")
        cats.append("he_b018_angioplasty")
        cats.append("he_b019_stroke_mini")
        cats.append("he_b020_stroke_PARQ")
        cats.append("he_c022_diabetes_PARQ")
        cats.append("he_c023_thyroid_disease_PARQ")
        cats.append("he_d027_tb_PARQ")
        cats.append("he_d028_cough_breathlessness")
        cats.append("he_d030_asthma_PARQ")
        cats.append("he_e031_epilepsy")
        cats.append("he_e032_migraine")
        cats.append("he_e033_parkinsons")
        cats.append("he_e034_ptsd")
        cats.append("he_e035_alzheimers")
        cats.append("he_e036_ms")
        cats.append("he_f037_celiac")
        cats.append("he_f038_lactose_intolerance")
        cats.append("he_f039_crohns")
        cats.append("he_f040_ulcerative_colitis")
        cats.append("he_f041_polyps")
        cats.append("he_f042_gallbladder_disease")
        cats.append("he_f043_stomach_ulcer")
        cats.append("he_f044_cirrhosis")
        cats.append("he_f045_fatty_liver")
        cats.append("he_f046_hepatitis_PARQ")
        cats.append("he_g047_ckd")
        cats.append("he_g048_esrd")
        cats.append("he_g049_kidney_stones")
        cats.append("he_g050_kidney_infection")
        cats.append("he_g051_pkd")
        cats.append("he_h052_allergic_reactions")
        cats.append("he_h053_scleroderma")
        cats.append("he_h054_shingles")
        cats.append("he_h055_fibromyalgia")
        cats.append("he_h056_lupus")
        cats.append("he_h057_sjogrens")
        cats.append("he_i058_hemochromatosis")
        cats.append("he_i059_iron_anemia")
        cats.append("he_i060_pernicious_anemia")
        cats.append("he_i061_sickle_cell")
        cats.append("he_j062_bone_loss")
        cats.append("he_j063_osteoporosis")
        cats.append("he_j064_gout")
        cats.append("he_j065_myositis")
        cats.append("he_j066_rheu_arthritis_PARQ")
        cats.append("he_j067_osteoarthritis_PARQ")
        cats.append("he_k069_psoriasis")
        cats.append("he_k070_eczema")
        cats.append("he_k071_urticaria")
        cats.append("he_k072_sunburn")
        cats.append("he_k073_scars")
        cats.append("he_l080_chronic_fatigue")
        cats.append("he_o103_cancer_PARQ")
        cats.append("he_q140_asbestos_PARQ")
        cats.append("he_q141_biohazards_PARQ")
        cats.append("he_q142_chemicals_PARQ")
        cats.append("he_q143_coal_dust_PARQ")
        cats.append("he_q144_coal_tar_PARQ")
        cats.append("he_q145_diesel_PARQ")
        cats.append("he_q146_dyes_PARQ")
        cats.append("he_q147_formaldehyde_PARQ")
        cats.append("he_q148_gasoline_PARQ")
        cats.append("he_q149_heavy_metals_PARQ")
        cats.append("he_q150_pesticide_PARQ")
        cats.append("he_q151_sand_PARQ")
        cats.append("he_q152_other_dust_PARQ")
        cats.append("he_q153_textiles_PARQ")
        cats.append("he_q154_wood_dust_PARQ")
        cats.append("he_q155_xrays_PARQ")
        cats.append("he_r166a_diabetes_mom")
        cats.append("he_r166b_diabetes_dad")
        cats.append("he_r167a_hbp_mom")
        cats.append("he_r167b_hbp_dad")
        cats.append("he_r168a_stroke_mom")
        cats.append("he_r168b_stroke_dad")
        cats.append("he_r169a_heart_attack_mom")
        cats.append("he_r169b_heart_attack_dad")
        cats.append("he_r170a_coronary_artery_mom")
        cats.append("he_r170b_coronary_artery_dad")
        cats.append("he_r171a_sickle_cell_mom")
        cats.append("he_r171b_sickle_cell_dad")
        cats.append("he_r172a_rheu_arthritis_mom")
        cats.append("he_r172b_rheu_arthritis_dad")
        cats.append("he_r173a_alzheimers_mom")
        cats.append("he_r173b_alzheimers_dad")
        cats.append("he_r174a_asthma_mom")
        cats.append("he_r174b_asthma_dad")
        cats.append("he_r175a_autism_mom")
        cats.append("he_r175b_autism_dad")
        cats.append("he_r176a_hayfever_mom")
        cats.append("he_r176b_hayfever_dad")
        cats.append("he_r177a_emphysema_mom")
        cats.append("he_r177b_emphysema_dad")
        cats.append("he_r178a_parkinsons_mom")
        cats.append("he_r178b_parkinsons_dad")
        cats.append("he_s185_smoke_indoors")
        cats.append("he_s187_alcohol_life_PARQ")
        cats.append("he_s192_sleep_hours")
        if type == "train": # only available for training data
            cats.append("he_b008_high_cholesterol") # ever diagnosed with high cholesterol

        return df[cats]
